#!/bin/bash
#
# httpd  Startup script for the Shibboleth Identity provider
#
# chkconfig: - 95 05
# description: Tomcat running Shibboleth IdP
#


# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/tomcat ]; then
        . /etc/sysconfig/tomcat
fi

# Set HTTPD=/usr/sbin/httpd.worker in /etc/sysconfig/httpd to use a server
# with the thread-based "worker" MPM; BE WARNED that some modules may not
# work correctly with a thread-based MPM; notably PHP will refuse to start.


JAVA_HOME=/usr
export JAVA_HOME
CATALINA_HOME=/opt/tomcat
export CATALINA_HOME

# Keystore & allocating a minimum memory size
JAVA_OPTS="-Xmx2000m -Didp.home=/opt/shibboleth-idp"
export JAVA_OPTS

prog=tomcat
RETVAL=0

# The semantics of these two functions differ from the way apachectl does
# things -- attempting to start while running is a failure, and shutdown
# when not running is also a failure.  So we just do it the way init scripts
# are expected to behave here.
start() {
        echo -n $"Starting $prog: "
	su tomcat -s /bin/sh -c $CATALINA_HOME/bin/startup.sh
        RETVAL=$?
        echo
        [ $RETVAL = 0 ]
        return $RETVAL
}
stop() {
       echo -n $"Stopping $prog: "
       ## Si l'arrêt ne fonctionne pas, au bout de 8 secondes un kill -KILL sera effectué
       #su tomcat -s /bin/sh -c "$CATALINA_HOME/bin/catalina.sh stop 8 -force"
       su tomcat -s /bin/sh -c $CATALINA_HOME/bin/shutdown.sh
       RETVAL=$?
       echo
       [ $RETVAL = 0 ]
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart)
  stop
  #make sure that tomcat is stopped before restarting it
  sleep 5
  start
  ;;
  condrestart)
  if [ -f ${pidfile} ] ; then
     stop
	start
	fi
	;;
  *)
  echo $"Usage: $prog {start|stop|restart|help}"
  exit 1
esac

exit $RETVAL
